### PR TITLE
Portable shell script and usage notes.

### PR DESCRIPTION
**Pull request by jm2dev**
Hi, and thanks for creating this cli tool, awesome work.

Let me suggest you those changes, to make it more portable, in my case I'm using ZSH as default shell on NixOS (so no /bin/bash for me as it happen on other systems). If you're interested on it you can get more information here: https://stackoverflow.com/questions/10376206/what-is-the-preferred-bash-shebang#comment102830783_52860837

I defaulted to 'sh' instead of 'bash' because it's what I always use and I got the expected results, 
```
% ./covid19-cli.sh -c Spain                                                                                                                    (master)
 ✔  Country: Spain
Cases: 19980, Deaths: 1002, Recovered: 1588
```

### CODE REVIEW

**Comment by garrylachman** [comment]
Thanks

**Comment by JanBrezina** [comment]
@jm2dev Are you sure your /bin/sh isn't simlinked to some other shell? This doesn't work with 'sh'

**Comment by garrylachman** [comment]
garrylachman@Garrys-MBP covid19-cli % sh covid19-cli.sh -c Spain 
 ✔  Country: Spain
Cases: 20412, Deaths: 1041, Recovered: 1588

**Comment by garrylachman** [comment]
ok... by sh is bash

**Comment by jm2dev** [comment]
@JanBrezina because of covid-19 situation I only have access to one system.

```
% which sh | xargs ls -lh                                                                                                                      
lrwxrwxrwx 1 root root 75 Jan  1  1970 /run/current-system/sw/bin/sh -> /nix/store/lb3hli8d9536g45mndwfwyi6fpny0blh-bash-interactive-4.4-p23/bin/sh
```

I'm using NixOS on that system, and as you can see there is no /bin/bash, and on top of my head I recall shells can live on /usr/local/bin whatsoever, but because they're available on the PATH variable they are found when you invoke them on the terminal. 

Unfortunately I found on my professional career that I can no rely on the existence of /bin/bash and I took this practice (several sysadmins recommended that approach on projects I was involved).

Of course, if a better solution is found, please do not hesitate to share it.

**Pull request merged**
